#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_challenge_create:
    path: /challenge/create
    controller: App\Controller\NewChallengeController::challenge


app_challenge_modify:
    path: /challenge/{id}/modify
    controller: App\Controller\NewChallengeController::challenge